### PR TITLE
fix: pagination placement and image size apm issues.

### PR DESCRIPTION
**Pull request by nistormihai**

### CODE REVIEW

**Comment by mstoltenburg** [comment]
It's not working locally - I have to dig deeper … sorry for not taking the time

**Comment by mstoltenburg** [comment]
I always get
> Unexpected end of JSON input

Could you please check this again?

**Comment by nistormihai** [comment]
due to the changes in the `package.json` a new `npm install` command is needed.

**Comment by mstoltenburg** [comment]
I know. I did …

**Pull request merged**
